/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package TP3.aerolinea;

import TP3.aerolinea.controller.exceptions.NonexistentEntityException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tincho
 */
public class Aplicacion extends javax.swing.JFrame {

    /**
     * Creates new form Aplicacion
     */
    public Aplicacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneContainer = new javax.swing.JTabbedPane();
        jTabbedPanePasajero = new javax.swing.JTabbedPane();
        jTextFieldPCrear = new javax.swing.JPanel();
        jTextFieldPApellido = new javax.swing.JTextField();
        jTextFieldPNombre = new javax.swing.JTextField();
        jTextFieldPDNI = new javax.swing.JTextField();
        jButtonPasajeroLimpiar = new javax.swing.JButton();
        jButtonPasajeroCrear = new javax.swing.JButton();
        jLabelPCApe = new javax.swing.JLabel();
        jLabelPCnombre = new javax.swing.JLabel();
        jLabelPCDNI = new javax.swing.JLabel();
        jPanelPLeer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePLTickets = new javax.swing.JTable();
        jLabelPLDNI = new javax.swing.JLabel();
        jLabelPLApe = new javax.swing.JLabel();
        jLabelPLnombre = new javax.swing.JLabel();
        jTextFieldPLDNI = new javax.swing.JTextField();
        jTextFieldPLApe = new javax.swing.JTextField();
        jTextFieldPLnombre = new javax.swing.JTextField();
        jLabelPLBuscar = new javax.swing.JLabel();
        jLabelPLBuscarDNI = new javax.swing.JLabel();
        jTextFieldPLBuscarDNI = new javax.swing.JTextField();
        jButtonPLBuscar = new javax.swing.JButton();
        jButtonPLLimpiar = new javax.swing.JButton();
        jPanelPModificar = new javax.swing.JPanel();
        jTextFieldPMDNI = new javax.swing.JTextField();
        jLabelPMDNI = new javax.swing.JLabel();
        jLabelPMApe = new javax.swing.JLabel();
        jLabelPMANombre = new javax.swing.JLabel();
        jTextFieldPMApe = new javax.swing.JTextField();
        jTextFieldPMNombre = new javax.swing.JTextField();
        jButtonPMGuardar = new javax.swing.JButton();
        jLabelPMBuscar = new javax.swing.JLabel();
        jTextFieldPMBuscar = new javax.swing.JTextField();
        jButtonPMBuscar = new javax.swing.JButton();
        jPanelPEliminar = new javax.swing.JPanel();
        jTextFieldPEDNI = new javax.swing.JTextField();
        jLabelPEDNI = new javax.swing.JLabel();
        jButtonPELimpiar = new javax.swing.JButton();
        jButtonPEliminarDatos = new javax.swing.JButton();
        jTabbedPaneTickets = new javax.swing.JTabbedPane();
        jPanelTCrear = new javax.swing.JPanel();
        jLabelTCCodigoVuelo = new javax.swing.JLabel();
        jLabelTCDNI = new javax.swing.JLabel();
        jLabelTCNumeroTicket = new javax.swing.JLabel();
        jTextFieldTCCodigoVuelo = new javax.swing.JTextField();
        jTextFieldTCDNI = new javax.swing.JTextField();
        jTextFieldTCNumeroTicket = new javax.swing.JTextField();
        jButtonTCCrear = new javax.swing.JButton();
        jButtonTCLimpiar = new javax.swing.JButton();
        jPanelTLeer = new javax.swing.JPanel();
        jLabelTLBuscar = new javax.swing.JLabel();
        jTextFieldTLNumeroTicketBusqueda = new javax.swing.JTextField();
        jButtonTLBuscar = new javax.swing.JButton();
        jButtonTLLimpiar = new javax.swing.JButton();
        jLabelTLCodigoVuelo = new javax.swing.JLabel();
        jTextFieldTLCodigoVuelo = new javax.swing.JTextField();
        jLabelTLDNI = new javax.swing.JLabel();
        jTextFieldTLDNI = new javax.swing.JTextField();
        jLabelTLNumeroTicket = new javax.swing.JLabel();
        jTextFieldTLNumeroTicketResultado = new javax.swing.JTextField();
        jLabelTLCodigoAeropuertoPartida = new javax.swing.JLabel();
        jTextFieldTLCodigoAeropuertoPartida = new javax.swing.JTextField();
        jLabelTLCodigoAeropuertoLlegada = new javax.swing.JLabel();
        jTextFieldTLCodigoAeropuertoLlegada = new javax.swing.JTextField();
        jPanelTModificar = new javax.swing.JPanel();
        jLabelTMBuscar = new javax.swing.JLabel();
        jLabelTMCodigoVuelo = new javax.swing.JLabel();
        jLabelTMDNI = new javax.swing.JLabel();
        jLabelTMNumeroTicket = new javax.swing.JLabel();
        jTextFieldTMCodigoVuelo = new javax.swing.JTextField();
        jTextFieldTMDNI = new javax.swing.JTextField();
        jTextFieldTMNumeroTicket = new javax.swing.JTextField();
        jTextFieldTMBuscar = new javax.swing.JTextField();
        jButtonTMBuscar = new javax.swing.JButton();
        jButtonTMModificar = new javax.swing.JButton();
        jPanelTEliminar = new javax.swing.JPanel();
        jLabelTENumeroTicket = new javax.swing.JLabel();
        jTextFieldTENumeroTicket = new javax.swing.JTextField();
        jButtonTEEliminar = new javax.swing.JButton();
        jTabbedPaneVuelo = new javax.swing.JTabbedPane();
        jPanelVCrear = new javax.swing.JPanel();
        jLabelVCCodigoVuelo = new javax.swing.JLabel();
        jLabelVCCodigoAeropuertoPartida = new javax.swing.JLabel();
        jLabelVCCodigoAeropuertoLlegada = new javax.swing.JLabel();
        jLabelVCPrecio = new javax.swing.JLabel();
        jTextFieldVCCodigoVuelo = new javax.swing.JTextField();
        jTextFieldVCCodigoAeropuertoPartida = new javax.swing.JTextField();
        jTextFieldVCAeropuertoLlegada = new javax.swing.JTextField();
        jTextFieldVCPrecio = new javax.swing.JTextField();
        jButtonVCCrear = new javax.swing.JButton();
        jButtonVCLimpiar = new javax.swing.JButton();
        jPanelVLeer = new javax.swing.JPanel();
        jPanelVModificar = new javax.swing.JPanel();
        jPanelVEliminar = new javax.swing.JPanel();
        jTabbedPaneAeropuerto1 = new javax.swing.JTabbedPane();
        jPanelACrear1 = new javax.swing.JPanel();
        jPanelALeer1 = new javax.swing.JPanel();
        jPanelAModificar1 = new javax.swing.JPanel();
        jPanelAEliminar1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor de Aerolíneas");

        jButtonPasajeroLimpiar.setText("Limpiar");
        jButtonPasajeroLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasajeroLimpiarActionPerformed(evt);
            }
        });

        jButtonPasajeroCrear.setText("Crear");
        jButtonPasajeroCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasajeroCrearActionPerformed(evt);
            }
        });

        jLabelPCApe.setText("Apellido");

        jLabelPCnombre.setText("Nombre");

        jLabelPCDNI.setText("DNI");

        javax.swing.GroupLayout jTextFieldPCrearLayout = new javax.swing.GroupLayout(jTextFieldPCrear);
        jTextFieldPCrear.setLayout(jTextFieldPCrearLayout);
        jTextFieldPCrearLayout.setHorizontalGroup(
            jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTextFieldPCrearLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldPCrearLayout.createSequentialGroup()
                        .addComponent(jButtonPasajeroCrear)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPasajeroLimpiar)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldPCrearLayout.createSequentialGroup()
                        .addGroup(jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jTextFieldPCrearLayout.createSequentialGroup()
                                .addComponent(jLabelPCnombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jTextFieldPCrearLayout.createSequentialGroup()
                                .addComponent(jLabelPCDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldPDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jTextFieldPCrearLayout.createSequentialGroup()
                                .addComponent(jLabelPCApe, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                                .addComponent(jTextFieldPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36))))
        );
        jTextFieldPCrearLayout.setVerticalGroup(
            jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTextFieldPCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jTextFieldPCrearLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelPCApe, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPCnombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPCDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(jTextFieldPCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPasajeroLimpiar)
                    .addComponent(jButtonPasajeroCrear))
                .addContainerGap())
        );

        jTabbedPanePasajero.addTab("Crear", jTextFieldPCrear);

        jTablePLTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "N°Ticket", "Codigo Vuelo", "Aeropuerto Partida", "Aeropuerto Destino"
            }
        ));
        jScrollPane1.setViewportView(jTablePLTickets);

        jLabelPLDNI.setText("DNI");

        jLabelPLApe.setText("Apellido");

        jLabelPLnombre.setText("Nombre");

        jTextFieldPLDNI.setEditable(false);

        jTextFieldPLApe.setEditable(false);

        jTextFieldPLnombre.setEditable(false);

        jLabelPLBuscar.setText("Buscar");

        jLabelPLBuscarDNI.setText("DNI");

        jTextFieldPLBuscarDNI.setText("Ingrese DNI");

        jButtonPLBuscar.setText("Buscar");
        jButtonPLBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLBuscarActionPerformed(evt);
            }
        });

        jButtonPLLimpiar.setText("Limpiar");
        jButtonPLLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPLLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPLeerLayout = new javax.swing.GroupLayout(jPanelPLeer);
        jPanelPLeer.setLayout(jPanelPLeerLayout);
        jPanelPLeerLayout.setHorizontalGroup(
            jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanelPLeerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelPLnombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPLApe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(jLabelPLDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldPLApe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jTextFieldPLDNI, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPLnombre))
                .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPLeerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                        .addComponent(jLabelPLBuscar)
                        .addGap(76, 76, 76))
                    .addGroup(jPanelPLeerLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabelPLBuscarDNI)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelPLeerLayout.createSequentialGroup()
                                .addComponent(jButtonPLBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonPLLimpiar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldPLBuscarDNI))
                        .addContainerGap())))
        );
        jPanelPLeerLayout.setVerticalGroup(
            jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPLeerLayout.createSequentialGroup()
                .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPLeerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPLDNI)
                            .addComponent(jTextFieldPLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelPLBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPLApe)
                    .addComponent(jTextFieldPLApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPLBuscarDNI)
                    .addComponent(jTextFieldPLBuscarDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPLnombre)
                    .addComponent(jTextFieldPLnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPLBuscar)
                    .addComponent(jButtonPLLimpiar))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE))
        );

        jTabbedPanePasajero.addTab("Leer", jPanelPLeer);

        jTextFieldPMDNI.setEditable(false);

        jLabelPMDNI.setText("DNI");

        jLabelPMApe.setText("Apellido");

        jLabelPMANombre.setText("Nombre");

        jButtonPMGuardar.setText("Guardar");
        jButtonPMGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPMGuardarActionPerformed(evt);
            }
        });

        jLabelPMBuscar.setText("Buscar DNI");

        jButtonPMBuscar.setText("Buscar");
        jButtonPMBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPMBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPModificarLayout = new javax.swing.GroupLayout(jPanelPModificar);
        jPanelPModificar.setLayout(jPanelPModificarLayout);
        jPanelPModificarLayout.setHorizontalGroup(
            jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPModificarLayout.createSequentialGroup()
                .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPModificarLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabelPMDNI)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPModificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelPMANombre)
                            .addComponent(jLabelPMApe))
                        .addGap(18, 18, 18)))
                .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldPMApe, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPMNombre)
                    .addComponent(jTextFieldPMDNI, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(112, 112, 112))
            .addGroup(jPanelPModificarLayout.createSequentialGroup()
                .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPModificarLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabelPMBuscar)
                        .addGap(35, 35, 35)
                        .addComponent(jTextFieldPMBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPMBuscar))
                    .addGroup(jPanelPModificarLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jButtonPMGuardar)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanelPModificarLayout.setVerticalGroup(
            jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPMDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPMDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPMApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPMApe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPMANombre)
                    .addComponent(jTextFieldPMNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButtonPMGuardar)
                .addGap(37, 37, 37)
                .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPMBuscar)
                    .addGroup(jPanelPModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPMBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonPMBuscar)))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        jTabbedPanePasajero.addTab("Modificar", jPanelPModificar);

        jLabelPEDNI.setText("DNI:");

        jButtonPELimpiar.setText("Limpiar");

        jButtonPEliminarDatos.setText("Eliminar");
        jButtonPEliminarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPEliminarDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelPEliminarLayout = new javax.swing.GroupLayout(jPanelPEliminar);
        jPanelPEliminar.setLayout(jPanelPEliminarLayout);
        jPanelPEliminarLayout.setHorizontalGroup(
            jPanelPEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPEDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPEliminarLayout.createSequentialGroup()
                        .addComponent(jButtonPEliminarDatos)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPELimpiar))
                    .addComponent(jTextFieldPEDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(297, Short.MAX_VALUE))
        );
        jPanelPEliminarLayout.setVerticalGroup(
            jPanelPEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPEDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPEDNI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPELimpiar)
                    .addComponent(jButtonPEliminarDatos))
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jTabbedPanePasajero.addTab("Eliminar", jPanelPEliminar);

        jTabbedPaneContainer.addTab("Pasajero", jTabbedPanePasajero);

        jLabelTCCodigoVuelo.setText("Código de Vuelo");

        jLabelTCDNI.setText("DNI de pasajero");

        jLabelTCNumeroTicket.setText("Número de Ticket");

        jButtonTCCrear.setText("Crear");

        jButtonTCLimpiar.setText("Limpiar");

        javax.swing.GroupLayout jPanelTCrearLayout = new javax.swing.GroupLayout(jPanelTCrear);
        jPanelTCrear.setLayout(jPanelTCrearLayout);
        jPanelTCrearLayout.setHorizontalGroup(
            jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTCrearLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jButtonTCCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTCLimpiar)
                        .addGap(242, 242, 242))
                    .addGroup(jPanelTCrearLayout.createSequentialGroup()
                        .addGroup(jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelTCNumeroTicket, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                            .addComponent(jLabelTCCodigoVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTCDNI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldTCCodigoVuelo)
                            .addComponent(jTextFieldTCDNI)
                            .addComponent(jTextFieldTCNumeroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(145, 145, 145))))
        );
        jPanelTCrearLayout.setVerticalGroup(
            jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTCCodigoVuelo)
                    .addComponent(jTextFieldTCCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTCDNI)
                    .addComponent(jTextFieldTCDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTCNumeroTicket)
                    .addComponent(jTextFieldTCNumeroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTCCrear)
                    .addComponent(jButtonTCLimpiar))
                .addContainerGap(266, Short.MAX_VALUE))
        );

        jTabbedPaneTickets.addTab("Crear", jPanelTCrear);

        jLabelTLBuscar.setText("Buscar");

        jTextFieldTLNumeroTicketBusqueda.setText("Ingresar número de ticket");

        jButtonTLBuscar.setText("Buscar");

        jButtonTLLimpiar.setText("Limpiar");

        jLabelTLCodigoVuelo.setText("Código de Vuelo");

        jTextFieldTLCodigoVuelo.setEditable(false);

        jLabelTLDNI.setText("DNI de Pasajero");

        jTextFieldTLDNI.setEditable(false);

        jLabelTLNumeroTicket.setText("Número de Ticket");

        jTextFieldTLNumeroTicketResultado.setEditable(false);

        jLabelTLCodigoAeropuertoPartida.setText("Código del Aeropuerto de Partida");

        jTextFieldTLCodigoAeropuertoPartida.setEditable(false);

        jLabelTLCodigoAeropuertoLlegada.setText("Código del Aeropuerto de Llegada");

        javax.swing.GroupLayout jPanelTLeerLayout = new javax.swing.GroupLayout(jPanelTLeer);
        jPanelTLeer.setLayout(jPanelTLeerLayout);
        jPanelTLeerLayout.setHorizontalGroup(
            jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTLeerLayout.createSequentialGroup()
                .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTLeerLayout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTLeerLayout.createSequentialGroup()
                                .addComponent(jButtonTLBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonTLLimpiar)
                                .addGap(28, 28, 28))
                            .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldTLNumeroTicketBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTLeerLayout.createSequentialGroup()
                                    .addComponent(jLabelTLBuscar)
                                    .addGap(65, 65, 65))))
                        .addGap(0, 229, Short.MAX_VALUE))
                    .addGroup(jPanelTLeerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTLNumeroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTLCodigoAeropuertoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTLCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTLNumeroTicketResultado, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTLCodigoAeropuertoPartida)
                            .addComponent(jTextFieldTLCodigoVuelo)
                            .addComponent(jTextFieldTLDNI)))
                    .addGroup(jPanelTLeerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTLCodigoAeropuertoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTLCodigoAeropuertoLlegada)))
                .addContainerGap())
        );
        jPanelTLeerLayout.setVerticalGroup(
            jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTLeerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTLBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldTLNumeroTicketBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTLBuscar)
                    .addComponent(jButtonTLLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTLCodigoVuelo)
                    .addComponent(jTextFieldTLCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTLDNI)
                    .addComponent(jTextFieldTLDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTLNumeroTicket)
                    .addComponent(jTextFieldTLNumeroTicketResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTLCodigoAeropuertoPartida)
                    .addComponent(jTextFieldTLCodigoAeropuertoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTLCodigoAeropuertoLlegada)
                    .addComponent(jTextFieldTLCodigoAeropuertoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        jTabbedPaneTickets.addTab("Leer", jPanelTLeer);

        jLabelTMBuscar.setText("Buscar número de ticket");

        jLabelTMCodigoVuelo.setText("Código de Vuelo");

        jLabelTMDNI.setText("DNI de Pasajero");

        jLabelTMNumeroTicket.setText("Número de Ticket");

        jTextFieldTMNumeroTicket.setEditable(false);

        jButtonTMBuscar.setText("Buscar");

        jButtonTMModificar.setText("Modificar");

        javax.swing.GroupLayout jPanelTModificarLayout = new javax.swing.GroupLayout(jPanelTModificar);
        jPanelTModificar.setLayout(jPanelTModificarLayout);
        jPanelTModificarLayout.setHorizontalGroup(
            jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTMCodigoVuelo)
                    .addComponent(jLabelTMDNI)
                    .addComponent(jLabelTMNumeroTicket)
                    .addComponent(jLabelTMBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTMModificar)
                    .addComponent(jButtonTMBuscar)
                    .addGroup(jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldTMCodigoVuelo)
                        .addComponent(jTextFieldTMDNI)
                        .addComponent(jTextFieldTMNumeroTicket)
                        .addComponent(jTextFieldTMBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanelTModificarLayout.setVerticalGroup(
            jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTModificarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTMBuscar)
                    .addComponent(jTextFieldTMBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTMBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTMCodigoVuelo)
                    .addComponent(jTextFieldTMCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTMDNI)
                    .addComponent(jTextFieldTMDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTMNumeroTicket)
                    .addComponent(jTextFieldTMNumeroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTMModificar)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        jTabbedPaneTickets.addTab("Modificar", jPanelTModificar);

        jLabelTENumeroTicket.setText("Número de Ticket");

        jButtonTEEliminar.setText("Eliminar");

        javax.swing.GroupLayout jPanelTEliminarLayout = new javax.swing.GroupLayout(jPanelTEliminar);
        jPanelTEliminar.setLayout(jPanelTEliminarLayout);
        jPanelTEliminarLayout.setHorizontalGroup(
            jPanelTEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTENumeroTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonTEEliminar)
                    .addComponent(jTextFieldTENumeroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanelTEliminarLayout.setVerticalGroup(
            jPanelTEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTEliminarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTENumeroTicket)
                    .addComponent(jTextFieldTENumeroTicket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTEEliminar)
                .addContainerGap(330, Short.MAX_VALUE))
        );

        jTabbedPaneTickets.addTab("Eliminar", jPanelTEliminar);

        jTabbedPaneContainer.addTab("Ticket", jTabbedPaneTickets);

        jLabelVCCodigoVuelo.setText("Código de Vuelo");

        jLabelVCCodigoAeropuertoPartida.setText("Código del Aeropuerto de Partida");

        jLabelVCCodigoAeropuertoLlegada.setText("Código del Aeropuerto de Llegada");

        jLabelVCPrecio.setText("Precio del Ticket");

        jButtonVCCrear.setText("Crear");

        jButtonVCLimpiar.setText("Limpiar");

        javax.swing.GroupLayout jPanelVCrearLayout = new javax.swing.GroupLayout(jPanelVCrear);
        jPanelVCrear.setLayout(jPanelVCrearLayout);
        jPanelVCrearLayout.setHorizontalGroup(
            jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVCCodigoAeropuertoLlegada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVCPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVCCodigoAeropuertoPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelVCCodigoVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVCrearLayout.createSequentialGroup()
                        .addComponent(jButtonVCCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonVCLimpiar))
                    .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextFieldVCCodigoVuelo)
                        .addComponent(jTextFieldVCCodigoAeropuertoPartida)
                        .addComponent(jTextFieldVCAeropuertoLlegada)
                        .addComponent(jTextFieldVCPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanelVCrearLayout.setVerticalGroup(
            jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVCCodigoVuelo)
                    .addComponent(jTextFieldVCCodigoVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVCCodigoAeropuertoPartida)
                    .addComponent(jTextFieldVCCodigoAeropuertoPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVCCodigoAeropuertoLlegada)
                    .addComponent(jTextFieldVCAeropuertoLlegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVCPrecio)
                    .addComponent(jTextFieldVCPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVCCrear)
                    .addComponent(jButtonVCLimpiar))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPaneVuelo.addTab("Crear", jPanelVCrear);

        javax.swing.GroupLayout jPanelVLeerLayout = new javax.swing.GroupLayout(jPanelVLeer);
        jPanelVLeer.setLayout(jPanelVLeerLayout);
        jPanelVLeerLayout.setHorizontalGroup(
            jPanelVLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelVLeerLayout.setVerticalGroup(
            jPanelVLeerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneVuelo.addTab("Leer", jPanelVLeer);

        javax.swing.GroupLayout jPanelVModificarLayout = new javax.swing.GroupLayout(jPanelVModificar);
        jPanelVModificar.setLayout(jPanelVModificarLayout);
        jPanelVModificarLayout.setHorizontalGroup(
            jPanelVModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelVModificarLayout.setVerticalGroup(
            jPanelVModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneVuelo.addTab("Modificar", jPanelVModificar);

        javax.swing.GroupLayout jPanelVEliminarLayout = new javax.swing.GroupLayout(jPanelVEliminar);
        jPanelVEliminar.setLayout(jPanelVEliminarLayout);
        jPanelVEliminarLayout.setHorizontalGroup(
            jPanelVEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelVEliminarLayout.setVerticalGroup(
            jPanelVEliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneVuelo.addTab("Eliminar", jPanelVEliminar);

        jTabbedPaneContainer.addTab("Vuelo", jTabbedPaneVuelo);

        javax.swing.GroupLayout jPanelACrear1Layout = new javax.swing.GroupLayout(jPanelACrear1);
        jPanelACrear1.setLayout(jPanelACrear1Layout);
        jPanelACrear1Layout.setHorizontalGroup(
            jPanelACrear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelACrear1Layout.setVerticalGroup(
            jPanelACrear1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneAeropuerto1.addTab("Crear", jPanelACrear1);

        javax.swing.GroupLayout jPanelALeer1Layout = new javax.swing.GroupLayout(jPanelALeer1);
        jPanelALeer1.setLayout(jPanelALeer1Layout);
        jPanelALeer1Layout.setHorizontalGroup(
            jPanelALeer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelALeer1Layout.setVerticalGroup(
            jPanelALeer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneAeropuerto1.addTab("Leer", jPanelALeer1);

        javax.swing.GroupLayout jPanelAModificar1Layout = new javax.swing.GroupLayout(jPanelAModificar1);
        jPanelAModificar1.setLayout(jPanelAModificar1Layout);
        jPanelAModificar1Layout.setHorizontalGroup(
            jPanelAModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelAModificar1Layout.setVerticalGroup(
            jPanelAModificar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneAeropuerto1.addTab("Modificar", jPanelAModificar1);

        javax.swing.GroupLayout jPanelAEliminar1Layout = new javax.swing.GroupLayout(jPanelAEliminar1);
        jPanelAEliminar1.setLayout(jPanelAEliminar1Layout);
        jPanelAEliminar1Layout.setHorizontalGroup(
            jPanelAEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        jPanelAEliminar1Layout.setVerticalGroup(
            jPanelAEliminar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jTabbedPaneAeropuerto1.addTab("Eliminar", jPanelAEliminar1);

        jTabbedPaneContainer.addTab("Aeropuerto", jTabbedPaneAeropuerto1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneContainer)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneContainer)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPasajeroLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasajeroLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPasajeroLimpiarActionPerformed

    private void jButtonPLBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLBuscarActionPerformed
        // TODO add your handling code here:
        Pasajero pasajero = Controladores.getPjc().findPasajero(Long.parseLong(jTextFieldPLBuscarDNI.getText()));
        Controladores.getVista().PLImprimirDatos(jTextFieldPLDNI, jTextFieldPLApe, jTextFieldPLnombre, jTablePLTickets, pasajero);
    }//GEN-LAST:event_jButtonPLBuscarActionPerformed

    private void jButtonPLLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPLLimpiarActionPerformed
        // TODO add your handling code here:
        Controladores.getVista().PLLimpiarDatos(jTextFieldPLBuscarDNI, jTextFieldPLDNI, jTextFieldPLApe, jTextFieldPLnombre, jTablePLTickets);
    }//GEN-LAST:event_jButtonPLLimpiarActionPerformed

    private void jButtonPMBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPMBuscarActionPerformed
        // TODO add your handling code here:
        Pasajero pasajero = Controladores.getPjc().findPasajero(Long.parseLong(jTextFieldPMBuscar.getText()));
        Controladores.getVista().PMImprimirDatos(jTextFieldPMDNI, jTextFieldPMApe, jTextFieldPMNombre, pasajero);
    }//GEN-LAST:event_jButtonPMBuscarActionPerformed

    private void jButtonPMGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPMGuardarActionPerformed
        try {
            // TODO add your handling code here:
            Controladores.getVista().PMModificarDatos(jTextFieldPMDNI, jTextFieldPMApe, jTextFieldPMNombre);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Aplicacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPMGuardarActionPerformed

    private void jButtonPasajeroCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasajeroCrearActionPerformed

        Controladores.getVista().PCrearPasajero(jTextFieldPDNI, jTextFieldPApellido, jTextFieldPNombre);
    }//GEN-LAST:event_jButtonPasajeroCrearActionPerformed

    private void jButtonPEliminarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPEliminarDatosActionPerformed
        Pasajero pasajero = Controladores.getPjc().findPasajero(Long.parseLong(jTextFieldPEDNI.getText()));
        Controladores.getVista().PEliminarDatos(jTextFieldPEDNI,pasajero);                                                   }//GEN-LAST:event_jButtonPEliminarDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aplicacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aplicacion().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPELimpiar;
    private javax.swing.JButton jButtonPEliminarDatos;
    private javax.swing.JButton jButtonPLBuscar;
    private javax.swing.JButton jButtonPLLimpiar;
    private javax.swing.JButton jButtonPMBuscar;
    private javax.swing.JButton jButtonPMGuardar;
    private javax.swing.JButton jButtonPasajeroCrear;
    private javax.swing.JButton jButtonPasajeroLimpiar;
    private javax.swing.JButton jButtonTCCrear;
    private javax.swing.JButton jButtonTCLimpiar;
    private javax.swing.JButton jButtonTEEliminar;
    private javax.swing.JButton jButtonTLBuscar;
    private javax.swing.JButton jButtonTLLimpiar;
    private javax.swing.JButton jButtonTMBuscar;
    private javax.swing.JButton jButtonTMModificar;
    private javax.swing.JButton jButtonVCCrear;
    private javax.swing.JButton jButtonVCLimpiar;
    private javax.swing.JLabel jLabelPCApe;
    private javax.swing.JLabel jLabelPCDNI;
    private javax.swing.JLabel jLabelPCnombre;
    private javax.swing.JLabel jLabelPEDNI;
    private javax.swing.JLabel jLabelPLApe;
    private javax.swing.JLabel jLabelPLBuscar;
    private javax.swing.JLabel jLabelPLBuscarDNI;
    private javax.swing.JLabel jLabelPLDNI;
    private javax.swing.JLabel jLabelPLnombre;
    private javax.swing.JLabel jLabelPMANombre;
    private javax.swing.JLabel jLabelPMApe;
    private javax.swing.JLabel jLabelPMBuscar;
    private javax.swing.JLabel jLabelPMDNI;
    private javax.swing.JLabel jLabelTCCodigoVuelo;
    private javax.swing.JLabel jLabelTCDNI;
    private javax.swing.JLabel jLabelTCNumeroTicket;
    private javax.swing.JLabel jLabelTENumeroTicket;
    private javax.swing.JLabel jLabelTLBuscar;
    private javax.swing.JLabel jLabelTLCodigoAeropuertoLlegada;
    private javax.swing.JLabel jLabelTLCodigoAeropuertoPartida;
    private javax.swing.JLabel jLabelTLCodigoVuelo;
    private javax.swing.JLabel jLabelTLDNI;
    private javax.swing.JLabel jLabelTLNumeroTicket;
    private javax.swing.JLabel jLabelTMBuscar;
    private javax.swing.JLabel jLabelTMCodigoVuelo;
    private javax.swing.JLabel jLabelTMDNI;
    private javax.swing.JLabel jLabelTMNumeroTicket;
    private javax.swing.JLabel jLabelVCCodigoAeropuertoLlegada;
    private javax.swing.JLabel jLabelVCCodigoAeropuertoPartida;
    private javax.swing.JLabel jLabelVCCodigoVuelo;
    private javax.swing.JLabel jLabelVCPrecio;
    private javax.swing.JPanel jPanelACrear1;
    private javax.swing.JPanel jPanelAEliminar1;
    private javax.swing.JPanel jPanelALeer1;
    private javax.swing.JPanel jPanelAModificar1;
    private javax.swing.JPanel jPanelPEliminar;
    private javax.swing.JPanel jPanelPLeer;
    private javax.swing.JPanel jPanelPModificar;
    private javax.swing.JPanel jPanelTCrear;
    private javax.swing.JPanel jPanelTEliminar;
    private javax.swing.JPanel jPanelTLeer;
    private javax.swing.JPanel jPanelTModificar;
    private javax.swing.JPanel jPanelVCrear;
    private javax.swing.JPanel jPanelVEliminar;
    private javax.swing.JPanel jPanelVLeer;
    private javax.swing.JPanel jPanelVModificar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPaneAeropuerto1;
    private javax.swing.JTabbedPane jTabbedPaneContainer;
    private javax.swing.JTabbedPane jTabbedPanePasajero;
    private javax.swing.JTabbedPane jTabbedPaneTickets;
    private javax.swing.JTabbedPane jTabbedPaneVuelo;
    private javax.swing.JTable jTablePLTickets;
    private javax.swing.JTextField jTextFieldPApellido;
    private javax.swing.JPanel jTextFieldPCrear;
    private javax.swing.JTextField jTextFieldPDNI;
    private javax.swing.JTextField jTextFieldPEDNI;
    private javax.swing.JTextField jTextFieldPLApe;
    private javax.swing.JTextField jTextFieldPLBuscarDNI;
    private javax.swing.JTextField jTextFieldPLDNI;
    private javax.swing.JTextField jTextFieldPLnombre;
    private javax.swing.JTextField jTextFieldPMApe;
    private javax.swing.JTextField jTextFieldPMBuscar;
    private javax.swing.JTextField jTextFieldPMDNI;
    private javax.swing.JTextField jTextFieldPMNombre;
    private javax.swing.JTextField jTextFieldPNombre;
    private javax.swing.JTextField jTextFieldTCCodigoVuelo;
    private javax.swing.JTextField jTextFieldTCDNI;
    private javax.swing.JTextField jTextFieldTCNumeroTicket;
    private javax.swing.JTextField jTextFieldTENumeroTicket;
    private javax.swing.JTextField jTextFieldTLCodigoAeropuertoLlegada;
    private javax.swing.JTextField jTextFieldTLCodigoAeropuertoPartida;
    private javax.swing.JTextField jTextFieldTLCodigoVuelo;
    private javax.swing.JTextField jTextFieldTLDNI;
    private javax.swing.JTextField jTextFieldTLNumeroTicketBusqueda;
    private javax.swing.JTextField jTextFieldTLNumeroTicketResultado;
    private javax.swing.JTextField jTextFieldTMBuscar;
    private javax.swing.JTextField jTextFieldTMCodigoVuelo;
    private javax.swing.JTextField jTextFieldTMDNI;
    private javax.swing.JTextField jTextFieldTMNumeroTicket;
    private javax.swing.JTextField jTextFieldVCAeropuertoLlegada;
    private javax.swing.JTextField jTextFieldVCCodigoAeropuertoPartida;
    private javax.swing.JTextField jTextFieldVCCodigoVuelo;
    private javax.swing.JTextField jTextFieldVCPrecio;
    // End of variables declaration//GEN-END:variables
}
